---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-query
spec:
  template:
    spec:
      containers:
      - name: db-query
        image: postgres:latest
        #command: ["/bin/bash",  "-c", "psql -h app-db.default -U app_user -p 5432 -d app-db -c \"select * from cars;\""]
        command: ["/bin/bash",  "-c", "psql -h app-db.default -U app_user -p 5432 -d app-db -f /tmp/app/app-db.sql"]
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: app-db-creds
                key: PGPASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/app
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: app-db-sql
  backoffLimit: 10

